name = "rps"
main = "src/index.js"
compatibility_date = "2024-12-18"

[[kv_namespaces]]
binding = "GAME_STATS"
id = "4a494562130246549c00eff601c72a48"
preview_id = "YOUR_KV_NAMESPACE_PREVIEW_ID"

[vars]
TELEGRAM_BOT_TOKEN = "توکن_ربات_تلگرام"

[env.production]
vars = { TELEGRAM_BOT_TOKEN = "توکن_ربات_تلگرام" }
